# Modal Symbolic Learning: Day 3

## Symbolic Land Cover Classification (*unimodal data*, *multimodal learning*)

In [1]:
using Pkg
Pkg.activate(".")
Pkg.instantiate()
Pkg.update()
Pkg.status()

  Activating project at `~/Desktop/modal-symbolic-learning-course`
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
  No Changes to `~/Desktop/modal-symbolic-learning-course/Project.toml`
  No Changes to `~/Desktop/modal-symbolic-learning-course/Manifest.toml`


Status `~/Desktop/modal-symbolic-learning-course/Project.toml`
  [acdeb78f] Catch22 v0.4.5
  [a93c6f00] DataFrames v1.6.1
  [864edb3b] DataStructures v0.18.15
  [7806a523] DecisionTree v0.12.4
  [7073ff75] IJulia v1.24.2
  [6a3955dd] ImageFiltering v0.7.8
  [033835bb] JLD2 v0.4.38
  [23992714] MAT v0.10.6
⌅ [add582a8] MLJ v0.19.5
  [c6f25543] MLJDecisionTreeInterface v0.4.0
  [e54bda2e] ModalDecisionTrees v0.3.6
  [91a5bcdd] Plots v1.39.0
  [7b3b3b3f] Sole v0.3.1
  [b002da8f] SoleLogics v0.6.14
  [4249d9c7] SoleModels v0.5.6
  [2913bbd2] StatsBase v0.34.2
  [9a3f8284] Random
Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated`


In [2]:
# Import libraries for statistics & Machine Learning
using Random
using DataFrames
using Plots
using StatsBase

using MLJ
using Sole

In [3]:
include("land-cover.jl")
data_dir = "data/"

X_df, y = LandCoverDataset(
    "Pavia University";
    window_size          = 3,
    ninstances_per_class = 40,
    pad_window_size      = 5,
);

Load LandCoverDataset: Pavia University...
window_size         = (3, 3)
pad_window_size     = (5, 5)
ninstances_per_class  = 40
ninstances_per_class_strategy = updownsampling
flattened           = false
apply_filter        = false
seed                = 1

Image size: (610, 340, 103)
class_counts_d = [("Asphalt", 1 => 6631), ("Meadows", 2 => 18649), ("Gravel", 3 => 2099), ("Trees", 4 => 3064), ("Painted metal sheets", 5 => 1345), ("Bare Soil", 6 => 5029), ("Bitumen", 7 => 1330), ("Self-Blocking Bricks", 8 => 3682), ("Shadows", 9 => 947)]
no_class_counts = 164624
n_classes = 9
ninstances = 40 * 9 = 360
effective_class_counts_d = [("Asphalt", 1 => 40), ("Meadows", 2 => 40), ("Gravel", 3 => 40), ("Trees", 4 => 40), ("Painted metal sheets", 5 => 40), ("Bare Soil", 6 => 40), ("Bitumen", 7 => 40), ("Self-Blocking Bricks", 8 => 40), ("Shadows", 9 => 40)]
countmap(labels) = Dict(5 => 40, 4 => 40, 6 => 40, 7 => 40, 2 => 40, 9 => 40, 8 => 40, 3 => 40, 1 => 40)


In [4]:
countmap(y)

Dict{String, Int64} with 9 entries:
  "Self-Blocking Bricks" => 40
  "Bitumen"              => 40
  "Gravel"               => 40
  "Bare Soil"            => 40
  "Painted metal sheets" => 40
  "Shadows"              => 40
  "Trees"                => 40
  "Asphalt"              => 40
  "Meadows"              => 40

In [5]:
length.(X_df)

360×103 DataFrame
 Row │ V1     V2     V3     V4     V5     V6     V7     V8     V9     V10    V ⋯
     │ Int64  Int64  Int64  Int64  Int64  Int64  Int64  Int64  Int64  Int64  I ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │     9      9      9      9      9      9      9      9      9      9    ⋯
   2 │     9      9      9      9      9      9      9      9      9      9
   3 │     9      9      9      9      9      9      9      9      9      9
   4 │     9      9      9      9      9      9      9      9      9      9
   5 │     9      9      9      9      9      9      9      9      9      9    ⋯
   6 │     9      9      9      9      9      9      9      9      9      9
   7 │     9      9      9      9      9      9      9      9      9      9
   8 │     9      9      9      9      9      9      9      9      9      9
   9 │     9      9      9      9      9      9      9      9      9      9    ⋯
  10 │     9      9      9      9      9      9      9      9      9      9
  11 │     9      9      9      9      9      9      9      9      9      9
  ⋮  │   ⋮      ⋮      ⋮      ⋮      ⋮      ⋮      ⋮      ⋮      ⋮      ⋮      ⋱
 351 │     9      9      9      9      9      9      9      9      9      9
 352 │     9      9      9      9      9      9      9      9      9      9    ⋯
 353 │     9      9      9      9      9      9      9      9      9      9
 354 │     9      9      9      9      9      9      9      9      9      9
 355 │     9      9      9      9      9      9      9      9      9      9
 356 │     9      9      9      9      9      9      9      9      9      9    ⋯
 357 │     9      9      9      9      9      9      9      9      9      9
 358 │     9      9      9      9      9      9      9      9      9      9
 359 │     9      9      9      9      9      9      9      9      9      9
 360 │     9      9      9      9      9      9      9      9      9      9    ⋯
                                                 93 columns and 339 rows omitted

In [49]:
X_df = broadcast(values->Matrix{Float64}(values), X_df)

360×103 DataFrame
 Row │ V1                                 V2                                 V ⋯
     │ Array…                             Array…                             A ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ [1186.0 1294.0 1291.0; 1701.0 17…  [1069.0 1177.0 1369.0; 1708.0 14…  [ ⋯
   2 │ [1153.0 1201.0 1563.0; 784.0 161…  [1024.0 1258.0 1480.0; 1024.0 15…  [
   3 │ [880.0 804.0 727.0; 672.0 865.0 …  [726.0 486.0 771.0; 498.0 629.0 …  [
   4 │ [1454.0 1082.0 1291.0; 512.0 985…  [1178.0 876.0 1229.0; 741.0 1014…  [
   5 │ [1603.0 1091.0 594.0; 1003.0 126…  [1602.0 1092.0 689.0; 804.0 1240…  [ ⋯
   6 │ [966.0 632.0 605.0; 482.0 669.0 …  [1171.0 630.0 451.0; 446.0 507.0…  [
   7 │ [1219.0 1459.0 1247.0; 1377.0 48…  [1377.0 1259.0 1255.0; 1298.0 88…  [
   8 │ [510.0 686.0 863.0; 637.0 748.0 …  [365.0 726.0 761.0; 810.0 639.0 …  [
   9 │ [541.0 814.0 1198.0; 857.0 1166.…  [530.0 676.0 910.0; 697.0 848.0 …  [ ⋯
  10 │ [856.0 302.0 568.0; 463.0 460.0 …  [698.0 291.0 598.0; 144.0 563.0 …  [
  11 │ [589.0 838.0 602.0; 1055.0 877.0…  [671.0 617.0 508.0; 800.0 688.0 …  [
  ⋮  │                 ⋮                                  ⋮                    ⋱
 351 │ [1300.0 1477.0 1108.0; 969.0 108…  [1289.0 1252.0 1139.0; 1172.0 10…  [
 352 │ [1505.0 1452.0 916.0; 1285.0 803…  [1230.0 1355.0 1085.0; 1304.0 10…  [ ⋯
 353 │ [1290.0 889.0 1183.0; 1408.0 673…  [1281.0 1061.0 1176.0; 989.0 949…  [
 354 │ [728.0 888.0 643.0; 162.0 586.0 …  [493.0 729.0 754.0; 485.0 367.0 …  [
 355 │ [462.0 546.0 801.0; 168.0 350.0 …  [539.0 362.0 800.0; 171.0 603.0 …  [
 356 │ [1072.0 652.0 1195.0; 1118.0 102…  [1049.0 724.0 962.0; 1128.0 1006…  [ ⋯
 357 │ [1310.0 727.0 908.0; 759.0 824.0…  [1364.0 780.0 947.0; 524.0 676.0…  [
 358 │ [1980.0 1828.0 1224.0; 1003.0 85…  [2001.0 1745.0 1178.0; 1065.0 63…  [
 359 │ [1672.0 1170.0 1006.0; 1785.0 12…  [1656.0 1129.0 873.0; 1746.0 118…  [
 360 │ [1206.0 494.0 969.0; 1037.0 587.…  [1140.0 818.0 659.0; 879.0 698.0…  [ ⋯
                                                101 columns and 339 rows omitted

In [50]:
# Let's unwind the spatial axes
X_df_static = Matrix(X_df)
cols = []
for i_var in 1:size(X_df_static, 2)
    var_unroll = cat(X_df_static[:,i_var]...; dims = 3)
    append!(cols, eachrow(reshape(var_unroll, (9, nrow(X_df)))))
end
X_df_static = DataFrame(cols, ["$n[$i][$j]" for n in names(X_df) for i in 1:3 for j in 1:3])

360×927 DataFrame
 Row │ V1[1][1]  V1[1][2]  V1[1][3]  V1[2][1]  V1[2][2]  V1[2][3]  V1[3][1]  V ⋯
     │ Float64   Float64   Float64   Float64   Float64   Float64   Float64   F ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │   1186.0    1701.0    1823.0    1294.0    1705.0    1359.0    1291.0    ⋯
   2 │   1153.0     784.0    1173.0    1201.0    1618.0    1071.0    1563.0
   3 │    880.0     672.0     540.0     804.0     865.0     757.0     727.0
   4 │   1454.0     512.0    1430.0    1082.0     985.0    1400.0    1291.0
   5 │   1603.0    1003.0    1222.0    1091.0    1260.0     801.0     594.0    ⋯
   6 │    966.0     482.0     427.0     632.0     669.0     811.0     605.0
   7 │   1219.0    1377.0    1187.0    1459.0     483.0     773.0    1247.0
   8 │    510.0     637.0     815.0     686.0     748.0     686.0     863.0
   9 │    541.0     857.0    1317.0     814.0    1166.0     620.0    1198.0    ⋯
  10 │    856.0     463.0     631.0     302.0     460.0     762.0     568.0
  11 │    589.0    1055.0     747.0     838.0     877.0    1016.0     602.0
  ⋮  │    ⋮         ⋮         ⋮         ⋮         ⋮         ⋮         ⋮        ⋱
 351 │   1300.0     969.0    1005.0    1477.0    1080.0     591.0    1108.0
 352 │   1505.0    1285.0     958.0    1452.0     803.0    1101.0     916.0    ⋯
 353 │   1290.0    1408.0    1292.0     889.0     673.0    1147.0    1183.0
 354 │    728.0     162.0     519.0     888.0     586.0     955.0     643.0
 355 │    462.0     168.0     570.0     546.0     350.0     813.0     801.0
 356 │   1072.0    1118.0    1557.0     652.0    1023.0     780.0    1195.0    ⋯
 357 │   1310.0     759.0     607.0     727.0     824.0     804.0     908.0
 358 │   1980.0    1003.0    1269.0    1828.0     859.0     780.0    1224.0
 359 │   1672.0    1785.0    1511.0    1170.0    1247.0    1431.0    1006.0
 360 │   1206.0    1037.0     503.0     494.0     587.0     382.0     969.0    ⋯
                                                920 columns and 339 rows omitted

In [51]:
using SoleData

X_multimodal = MultiModalDataset([X_df, X_df_static])

● MultiModalDataset{DataFrame}
   └─ dimensionalities: (2, 0)
- Modality 1 / 2
   └─ dimensionality: 2
360×103 SubDataFrame
 Row │ V1                                 V2                                 V ⋯
     │ Array…                             Array…                             A ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ [1186.0 1294.0 1291.0; 1701.0 17…  [1069.0 1177.0 1369.0; 1708.0 14…  [ ⋯
   2 │ [1153.0 1201.0 1563.0; 784.0 161…  [1024.0 1258.0 1480.0; 1024.0 15…  [
   3 │ [880.0 804.0 727.0; 672.0 865.0 …  [726.0 486.0 771.0; 498.0 629.0 …  [
   4 │ [1454.0 1082.0 1291.0; 512.0 985…  [1178.0 876.0 1229.0; 741.0 1014…  [
   5 │ [1603.0 1091.0 594.0; 1003.0 126…  [1602.0 1092.0 689.0; 804.0 1240…  [ ⋯
   6 │ [966.0 632.0 605.0; 482.0 669.0 …  [1171.0 630.0 451.0; 446.0 507.0…  [
   7 │ [1219.0 1459.0 1247.0; 1377.0 48…  [1377.0 1259.0 1255.0; 1298.0 88…  [
   8 │ [510.0 686.0 863.0; 637.0 748.0 …  [365.0 726.0 761.0; 810.0 639.0 … 

In [52]:
using ModalDecisionTrees

model = ModalDecisionTree(; relations = :RCC8)

ModalDecisionTree(
  max_depth = nothing, 
  min_samples_leaf = 4, 
  min_purity_increase = 0.002, 
  max_purity_at_leaf = Inf, 
  max_modal_depth = nothing, 
  relations = :RCC8, 
  features = nothing, 
  conditions = nothing, 
  featvaltype = Float64, 
  initconditions = nothing, 
  downsize = ModalDecisionTrees.MLJInterface.var"#downsize#43"(), 
  print_progress = false, 
  rng = Random._GLOBAL_RNG(), 
  display_depth = nothing, 
  min_samples_split = nothing, 
  n_subfeatures = identity, 
  post_prune = false, 
  merge_purity_threshold = nothing, 
  feature_importance = :split)

In [28]:
# Train in cross-validation!
e = @time evaluate!(machine(model, X_multimodal, y);
    resampling=StratifiedCV(rng = Random.Xoshiro(1), shuffle=true, nfolds = 10),
    measures=[accuracy],
    verbosity=0,
    check_measure=false
)

[ Info: Precomputing logiset...
┌ Warning: ScalarOneStepMemoset: Found globalrel in relations in a single-world case.
└ @ SoleModels ~/.julia/packages/SoleModels/xvfwj/src/logisets/scalar/onestep-memoset.jl:304


694.598215 seconds (7.75 G allocations: 729.113 GiB, 11.43% gc time, 12.83% compilation time: <1% of which was recompilation)


PerformanceEvaluation object with these fields:
  model, measure, operation, measurement, per_fold,
  per_observation, fitted_params_per_fold,
  report_per_fold, train_test_rows, resampling, repeats
Extract:
┌────────────┬──────────────┬─────────────┬─────────┬───────────────────────────
│ measure    │ operation    │ measurement │ 1.96*SE │ per_fold                 ⋯
├────────────┼──────────────┼─────────────┼─────────┼───────────────────────────
│ Accuracy() │ predict_mode │ 0.775       │ 0.0537  │ [0.778, 0.833, 0.611, 0. ⋯
└────────────┴──────────────┴─────────────┴─────────┴───────────────────────────
                                                                1 column omitted


In [29]:
# Test accuracies per fold
e.per_fold

1-element Vector{Vector{Float64}}:
 [0.7777777777777778, 0.8333333333333334, 0.6111111111111112, 0.9166666666666666, 0.7777777777777778, 0.7777777777777778, 0.6944444444444444, 0.75, 0.7777777777777778, 0.8333333333333334]

In [30]:
trees = map((((train_idxs, test_idxs), rep),)->begin
    predictions, tree_test = rep.sprinkle(slicedataset(X_multimodal, test_idxs), y[test_idxs]; simplify = true)
    tree_test
end, zip(e.train_test_rows, e.report_per_fold))

10-element Vector{DecisionTree{String, MultiFormula{Atom{ScalarCondition{Int64, SoleModels.UnivariateValue, ScalarMetaCondition{SoleModels.UnivariateValue, typeof(>=)}}}}, SoleModels.ConstantModel{String}}}:
 ▣ {2}(V923 ≥ 1714)
├✔ {2}(V52 ≥ 1122)
│├✔ {2}(V248 ≥ 1882)
││├✔ Painted metal sheets
││└✘ {1}(⟨G⟩(min[V47] ≥ 2103))
││ ├✔ Gravel
││ └✘ {2}(V178 ≥ 1476)
││  ├✔ Self-Blocking Bricks
││  └✘ {1}(⟨G⟩(min[V2] < 1021))
││   ├✔ Self-Blocking Bricks
││   └✘ Gravel
│└✘ {1}(⟨G⟩(min[V68] < 563))
│ ├✔ Trees
│ └✘ {1}(⟨G⟩(min[V29] ≥ 1347))
│  ├✔ Bare Soil
│  └✘ {2}(V662 ≥ 1915)
│   ├✔ Meadows
│   └✘ {2}(V63 ≥ 579)
│    ├✔ Meadows
│    └✘ Bare Soil
└✘ {1}(⟨G⟩(min[V6] < 567))
 ├✔ Shadows
 └✘ {2}(V593 ≥ 1343)
  ├✔ {2}(V917 ≥ 1490)
  │├✔ Gravel
  │└✘ {1}(⟨G⟩(min[V3] < 754))
  │ ├✔ Asphalt
  │ └✘ Bitumen
  └✘ Asphalt

 ▣ {2}(V923 ≥ 1714)
├✔ {2}(V44 ≥ 1109)
│├✔ {1}(⟨G⟩(min[V38] ≥ 2424))
││├✔ Painted metal sheets
││└✘ {1}(⟨G⟩(min[V67] ≥ 2152))
││ ├✔ Gravel
││ └✘ {2}(V743 ≥ 1919)
││  ├✔ Self-Blocking Br

In [31]:
rules = vcat(listrules.(trees)...)

134-element Vector{Rule{String, A, SoleModels.ConstantModel{String}} where A<:Formula}:
 ▣ {2}(V248 ≥ 1882)  🠮  Painted metal sheets

 ▣ {1}(⟨G⟩(min[V47] ≥ 2103)) ∧ {2}(V52 ≥ 1122) ∧ (V248 < 1882)  🠮  Gravel

 ▣ {1}([G](min[V47] < 2103)) ∧ {2}(V178 ≥ 1476) ∧ (V248 < 1882)  🠮  Self-Blocking Bricks

 ▣ {1}⟨G⟩(min[V2] < 1021) ∧ [G](min[V47] < 2103) ∧ {2}(V52 ≥ 1122) ∧ (V248 < 1882) ∧ (V178 < 1476)  🠮  Self-Blocking Bricks

 ▣ {1}[G](min[V47] < 2103) ∧ [G](min[V2] ≥ 1021) ∧ {2}(V52 ≥ 1122) ∧ (V248 < 1882) ∧ (V178 < 1476)  🠮  Gravel

 ▣ {1}(⟨G⟩(min[V68] < 563)) ∧ {2}(V923 ≥ 1714) ∧ (V52 < 1122)  🠮  Trees

 ▣ {1}⟨G⟩(min[V29] ≥ 1347) ∧ [G](min[V68] ≥ 563) ∧ {2}(V923 ≥ 1714) ∧ (V52 < 1122)  🠮  Bare Soil

 ▣ {1}[G](min[V68] ≥ 563) ∧ [G](min[V29] < 1347) ∧ {2}(V662 ≥ 1915) ∧ (V52 < 1122)  🠮  Meadows

 ▣ {1}[G](min[V68] ≥ 563) ∧ [G](min[V29] < 1347) ∧ {2}(V63 ≥ 579) ∧ (V52 < 1122) ∧ (V662 < 1915)  🠮  Meadows

 ▣ {1}[G](min[V68] ≥ 563) ∧ [G](min[V29] < 1347) ∧ {2}(V923 ≥ 1714) ∧ (V52 < 1122) ∧ (V6

In [32]:
# Every symbolic model (including rules) can have has additional information attached
println(rules[1])

ruleinfo = SoleModels.info(rules[1])
println(keys(ruleinfo))

▣ {2}(V248 ≥ 1882)  🠮  Painted metal sheets

(:supporting_labels, :supporting_predictions, :shortform)


In [33]:
ruleinfo[:supporting_predictions] |> length

4

In [34]:
sort(readmetrics.(rules), by=x->x[:coverage], rev = true)

134-element Vector{NamedTuple{(:ninstances, :confidence, :coverage), Tuple{Int64, Float64, Float64}}}:
 (ninstances = 7, confidence = 0.57, coverage = 0.19)
 (ninstances = 6, confidence = 0.67, coverage = 0.17)
 (ninstances = 6, confidence = 0.67, coverage = 0.17)
 (ninstances = 6, confidence = 0.67, coverage = 0.17)
 (ninstances = 6, confidence = 0.67, coverage = 0.17)
 (ninstances = 5, confidence = 0.4, coverage = 0.14)
 (ninstances = 5, confidence = 0.4, coverage = 0.14)
 (ninstances = 5, confidence = 0.8, coverage = 0.14)
 (ninstances = 5, confidence = 0.6, coverage = 0.14)
 (ninstances = 5, confidence = 0.8, coverage = 0.14)
 (ninstances = 5, confidence = 0.8, coverage = 0.14)
 (ninstances = 5, confidence = 0.6, coverage = 0.14)
 (ninstances = 5, confidence = 0.6, coverage = 0.14)
 ⋮
 (ninstances = 1, confidence = 0.0, coverage = 0.03)
 (ninstances = 1, confidence = 0.0, coverage = 0.03)
 (ninstances = 1, confidence = 1.0, coverage = 0.03)
 (ninstances = 1, confidence = 0.0, cover

In [53]:
# goodrules = filter(r->readmetrics(r)[:ninstances] > 1, rules)
goodrules = sort(rules, by=r->readmetrics(r)[:coverage], rev = true)
printmodel.(goodrules; show_metrics = true, threshold_digits = 4);

▣ {2}(V52 ≥ 1114.0) ∧ (V248 < 1882.0)  🠮  Self-Blocking Bricks : (ninstances = 7, confidence = 0.57, coverage = 0.19)
▣ {1}⟨G⟩(min[V44] < 543.0) ∧ [G]((min[V44] < 543.0) → [N̅T̅P̅P̅](min[V28] < 620.0)) ∧ {2}(V923 ≥ 1714.0) ∧ (V44 < 1109.0)  🠮  Trees : (ninstances = 6, confidence = 0.67, coverage = 0.17)
▣ {2}(V540 ≥ 428.0) ∧ (V52 < 1114.0)  🠮  Meadows : (ninstances = 6, confidence = 0.67, coverage = 0.17)
▣ {2}(V52 ≥ 1114.0) ∧ (V248 < 1882.0)  🠮  Self-Blocking Bricks : (ninstances = 6, confidence = 0.67, coverage = 0.17)
▣ {1}([G](min[V6] ≥ 567.0)) ∧ {2}(V593 ≥ 1343.0) ∧ (V923 < 1714.0)  🠮  Bitumen : (ninstances = 6, confidence = 0.67, coverage = 0.17)
▣ {1}[G](min[V68] ≥ 563.0) ∧ [G](min[V29] < 1347.0) ∧ {2}(V923 ≥ 1714.0) ∧ (V52 < 1114.0) ∧ (V877 < 2483.0)  🠮  Bare Soil : (ninstances = 5, confidence = 0.4, coverage = 0.14)
▣ {1}([G](min[V48] < 2114.0)) ∧ {2}(V197 ≥ 1459.0) ∧ (V248 < 1882.0)  🠮  Self-Blocking Bricks : (ninstances = 5, confidence = 0.4, coverage = 0.14)
▣ {1}(⟨G⟩(min[V

▣ {1}(⟨G⟩((min[V44] < 543.0) ∧ ⟨N̅T̅P̅P̅⟩(min[V28] ≥ 620.0))) ∧ {2}(V923 ≥ 1714.0) ∧ (V44 < 1109.0)  🠮  Meadows : (ninstances = 2, confidence = 1.0, coverage = 0.06)
▣ {1}⟨G⟩(min[V4] < 1185.0) ∧ [G](min[V38] < 2267.0) ∧ {2}(V167 ≥ 1475.0)  🠮  Self-Blocking Bricks : (ninstances = 2, confidence = 0.5, coverage = 0.06)
▣ {1}([G](min[V38] < 2267.0)) ∧ {2}(V52 ≥ 1114.0) ∧ (V167 < 1475.0)  🠮  Gravel : (ninstances = 2, confidence = 0.0, coverage = 0.06)
▣ {1}(⟨G⟩(min[V68] < 563.0)) ∧ {2}(V923 ≥ 1714.0) ∧ (V52 < 1114.0)  🠮  Trees : (ninstances = 2, confidence = 1.0, coverage = 0.06)
▣ {1}⟨G⟩(min[V29] ≥ 1347.0) ∧ [G](min[V68] ≥ 563.0) ∧ {2}(V923 ≥ 1714.0) ∧ (V52 < 1114.0)  🠮  Bare Soil : (ninstances = 2, confidence = 0.5, coverage = 0.06)
▣ {1}([G](min[V5] ≥ 516.0)) ∧ {2}(V917 ≥ 1490.0) ∧ (V923 < 1714.0) ∧ (V106 < 1346.0)  🠮  Gravel : (ninstances = 2, confidence = 1.0, coverage = 0.06)
▣ {1}([G](min[V1] < 2642.0)) ∧ {2}(V248 ≥ 1882.0)  🠮  Bare Soil : (ninstances = 2, confidence = 1.0, coverage 